### PR TITLE
Update recipe for v5.2

### PR DESCRIPTION
**Pull request by paugier**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by paugier** [comment]
@conda-forge-admin, please rerender

**Comment by ngoldbaum** [comment]
Mercurial upstream recommends using python3 for Mercurial 5.2 on Linux and Mac. Perhaps we should be following their lead?

https://www.mercurial-scm.org/pipermail/mercurial-packaging/2019-October/000282.html

I idle in #mercurial on freenode if you want to chat more about this in a more low-latency context with other people who are intereseted in mercurial.

**Comment by ngoldbaum** [comment]
@conda-forge-admin, please rerender

**Comment by paugier** [comment]
> Mercurial upstream recommends using python3 for Mercurial 5.2 on Linux and Mac. Perhaps we should be following their lead?

Yes! If core-devs say Mercurial is ready, let's do it.

I just tried `skip: True  # [win and py3k]` but it does not seem sufficient...

**Comment by ngoldbaum** [comment]
Mercurial does some pretty non-standard stuff with distutils, it's possible that using pip as suggested by the lint will break things. I guess let's see if the tests fail :)

**Comment by ngoldbaum** [comment]
> I just tried skip: True # [win and py3k] but it does not seem sufficient...

You also need to rerender the feedstock, which I just tried to do and isn't working. Let me check in on conda-forge's gitter...

**Pull request merged**
