### PR TITLE
Mercurial 4.9.1

### PR DESCRIPTION
**Pull request by paugier**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@conda-smithy please rerender

**Comment by ngoldbaum** [comment]
@conda-forge-admin please rerender

**Comment by paugier** [comment]
@ngoldbaum

I created this PR in order to be able to install a recent version of Mercurial (supporting `hg absorb`) with conda (in particular useful on Windows).

Do you think it can be merged so that the conda package would be built?

**Comment by ngoldbaum** [comment]
Please feel free to make a PR and add yourself as a maintainer.

**Pull request merged**
